### ISSUE TITLE
Shipping type added in master is not showing in shipping type dropdown

### ISSUE THREAD

**Issue by Parikshit0927** [Unesync/warehouse-inventory#29]
Can not see shipping type test - 7 in shipping type dropdown.

![Image](https://user-images.githubusercontent.com/83452577/211265258-848eb161-1fce-47be-b059-03e132910efc.png)

**Comment by amitjamipara** [comment]
This issue resolved..pls check @Parikshit0927

**Comment by Parikshit0927** [comment]
I can still see same issue . @amitjamipara

**Comment by Parikshit0927** [comment]
This is working now.
