### ISSUE TITLE
Tax type added in master is not showing in tax type dropdown

### ISSUE THREAD

**Issue by Parikshit0927** [Unesync/warehouse-inventory#30]
Only few added tax types are showing and other are not in tax type dropdown in any form like purchase, sales etc. 

![Image](https://user-images.githubusercontent.com/83452577/211267432-d370bbba-c1fb-43d8-9873-b323e176da14.png)

**Comment by amitjamipara** [comment]
This issue resolved..pls check @Parikshit0927

**Comment by Parikshit0927** [comment]
I can still see same issue . @amitjamipara

**Comment by Parikshit0927** [comment]
This is working now.
